version: "2.4"
services:

## Usage: 
#   $> docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.sugcon.yml up -d
# .. and to bring all containers down again
#   $> docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.sugcon.yml down
##

  # mvp-rendering:
  #   scale: 0

  sugcon-eu-rendering:
    container_name: sugcon-eu-rendering
    image: ${MVP_DOCKER_REGISTRY}sugcon-rendering:${SITECORE_VERSION}
    volumes:
      - .\:C:\solution
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://*:80"
      Sitecore__InstanceUri: "http://cd"
      Sitecore__RenderingHostUri: "https://${SUGCON_EU_RENDERING_HOST}"
      Sitecore__EnableExperienceEditor: "true"
      Sitecore__DefaultSiteName: "sugcon-eu"
      Application_User_Name: ${SITECORE_APPLICATION_USER_NAME}
      Application_User_Password: ${SITECORE_APPLICATION_USER_PASSWORD}
      Application_User_Domain: ${SITECORE_APPLICATION_USER_DOMAIIN}
      Application_CMS_URL: ${SITECORE_Application_CMS_URL}
    ports:
      - "80"      
    mem_limit: ${MEM_LIMIT_RENDERING:-1GB}           
    depends_on:
      - sugcon-rendering
      - cm
      - cd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sugcon-eu-secure.entrypoints=websecure"
      - "traefik.http.routers.sugcon-eu-secure.rule=Host(`${SUGCON_EU_RENDERING_HOST}`)"
      - "traefik.http.routers.sugcon-eu-secure.tls=true"
      - "traefik.http.routers.sugcon-eu.entrypoints=web"
      - "traefik.http.routers.sugcon-eu.rule=Host(`${SUGCON_EU_RENDERING_HOST}`)"
      - "traefik.http.routers.sugcon-eu.tls=false"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 60s
      timeout: 30s

  # sugcon-anz-rendering:
  #   container_name: sugcon-anz-rendering
  #   image: ${MVP_DOCKER_REGISTRY}sugcon-rendering:${SITECORE_VERSION}
  #   volumes:
  #     - .\:C:\solution
  #   environment:
  #     ASPNETCORE_ENVIRONMENT: "Development"
  #     ASPNETCORE_URLS: "http://*:80"
  #     Sitecore__InstanceUri: "http://cd"
  #     Sitecore__RenderingHostUri: "https://${SUGCON_ANZ_RENDERING_HOST}"
  #     Sitecore__EnableExperienceEditor: "true"
  #     Sitecore__DefaultSiteName: "sugcon-anz"
  #     Application_User_Name: ${SITECORE_APPLICATION_USER_NAME}
  #     Application_User_Password: ${SITECORE_APPLICATION_USER_PASSWORD}
  #     Application_User_Domain: ${SITECORE_APPLICATION_USER_DOMAIIN}
  #     Application_CMS_URL: ${SITECORE_Application_CMS_URL}
  #   ports:
  #     - "80"      
  #   mem_limit: ${MEM_LIMIT_RENDERING:-1GB}           
  #   depends_on:
  #     - sugcon-rendering
  #     - cm
  #     - cd
  #   labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.sugcon-anz-secure.entrypoints=websecure"
  #    - "traefik.http.routers.sugcon-anz-secure.rule=Host(`${SUGCON_ANZ_RENDERING_HOST}`)"
  #    - "traefik.http.routers.sugcon-anz-secure.tls=true"
  #    - "traefik.http.routers.sugcon-anz.entrypoints=web"
  #    - "traefik.http.routers.sugcon-anz.rule=Host(`${SUGCON_ANZ_RENDERING_HOST}`)"
  #    - "traefik.http.routers.sugcon-anz.tls=false"  
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost/healthz"]
  #     interval: 60s
  #     timeout: 30s      

  cm:
    environment:
      SUGCON_EU_RENDERING_HOST_PUBLIC_URI: https://${SUGCON_EU_RENDERING_HOST}
#      SUGCON_ANZ_RENDERING_HOST_PUBLIC_URI: https://${SUGCON_ANZ_RENDERING_HOST}      
