---
ID: "e2b28a3c-45a2-45cf-a7b6-ddd768fc4e58"
Parent: "e454a4e3-f69a-4d46-8601-eda00669d470"
Template: "e454a4e3-f69a-4d46-8601-eda00669d470"
Path: /sitecore/templates/Feature/Navigation/Top Links Collection/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{E4986869-E4B1-4990-8669-52ABF69CD9CF}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200528T230118Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "242883e1-b546-4477-8c66-7e1a2d6e326b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200528T230228Z
