apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: mssql
  newName: $(ACR_ENDPOINT)/mvp-mssql
  newTag: $(Build.BuildNumber)-$(Build.SourceBranchName)
- name: solr
  newName: solr
  newTag: 8.4.0

resources:
  - mssql.yaml
  - solr.yaml