generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: sitecore-admin
  files:
  - sitecore-adminpassword.txt
- name: sitecore-database
  files:
  - sitecore-databaseusername.txt
  - sitecore-databasepassword.txt
  - sitecore-databaseservername.txt
  - sitecore-database-elastic-pool-name.txt
  - sitecore-master-database-username.txt
  - sitecore-master-database-password.txt
  - sitecore-core-database-username.txt
  - sitecore-core-database-password.txt
  - sitecore-web-database-username.txt
  - sitecore-web-database-password.txt
  - sitecore-forms-database-username.txt
  - sitecore-forms-database-password.txt
- name: sitecore-identitycertificate
  files:
  - sitecore-identitycertificate.txt
  - sitecore-identitycertificatepassword.txt
- name: sitecore-license
  files:
  - sitecore-license.txt
- name: sitecore-identity
  files:
  - sitecore-identitysecret.txt
  - sitecore-identitysecret_mvp.txt
- name: sitecore-telerik
  files:
  - sitecore-telerikencryptionkey.txt
- name: sitecore-solr
  files:
  - sitecore-solr-connection-string.txt
- name: staging-tls
  files:
    - tls/staging/tls.key
    - tls/staging/tls.crt
  type: kubernetes.io/tls