apiVersion: v1
kind: Service
metadata:
  name: mvp-rendering
spec:
  selector:
    app: mvp-rendering
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-rendering
  labels:
    app: mvp-rendering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvp-rendering
  template:
    metadata:
      labels:
        app: mvp-rendering
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-mvp-rendering
        image: sitecore-mvp-rendering
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Release
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: Sitecore__InstanceUri
          value: http://cd
        - name: Sitecore__RenderingHostUri
          value: https://$(PROD_HOST)/
        - name: Sitecore__EnableExperienceEditor
          value: "true"
        - name: Sitecore_License
          valueFrom:
            secretKeyRef:
              name: sitecore-license
              key: sitecore-license.txt
        - name: Okta__OktaDomain
          valueFrom:
            secretKeyRef:
              name: okta
              key: okta-domain.txt
        - name: Okta__ClientId
          valueFrom:
            secretKeyRef:
              name: okta
              key: okta-client-id.txt
        - name: Okta__ClientSecret
          valueFrom:
            secretKeyRef:
              name: okta
              key: okta-domain.txt
        - name: Okta__AuthorizationServerId
          valueFrom:
            secretKeyRef:
              name: okta
              key: okta-auth-server-id.txt
        - name: PeopleGraphQL__UrlLive
          value: http://cd/api/content/people
        - name: PeopleGraphQL__UrlEdit
          value: http://cd/api/content/people
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 60
          periodSeconds: 30
          failureThreshold: 3
      imagePullSecrets:
      - name: regcred