---
ID: "9c05e623-3031-4a61-b75f-34e5edb92da0"
Parent: "a054184c-3b20-4c2b-ab04-c8a03acd5522"
Template: "a054184c-3b20-4c2b-ab04-c8a03acd5522"
Path: /sitecore/templates/Project/MvpSite/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {6AEC120A-7222-42C6-A8E8-53F9354AEF53}
    {EF8DD6F4-1BB8-4831-A1A6-DEFA3594051A}
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{1AE49D12-8DA1-4FBD-92FF-887B01C02BB5}">
        <r
          ds="{C4DADD5E-1521-4C6D-AFCE-39D237751541}"
          id="{A4F28B31-5D18-4158-92AB-F4D2ECA6D2BE}"
          par=""
          ph="header"
          uid="{19CCAD6A-4C17-48CC-B78A-5CE8415E279F}" />
        <r
          id="{C9593FF9-14AC-4C8E-B217-D85C05ADEAD7}"
          ph="header"
          uid="{D842E8EB-450E-4348-A54A-E60CF16E9E52}" />
        <r
          id="{437CCC09-AB5D-47B3-96D7-2B05BDFF5324}"
          ph="footer"
          uid="{64CD74AD-6939-48FB-ABB9-33F2403ED031}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200604T041834Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f8032c68-2d98-41ac-afbd-a85f5dc197dc"
    - ID: "b1ece12f-b2c9-44e6-92a3-c5dfd6514b59"
      Hint: Menu Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200728T082144Z
    - ID: "efc0a3c7-6993-47d2-ba85-10b44961916e"
      Hint: Include in Menu
      Value: 1
