---
ID: "b70bb943-d9fb-4810-a823-eb1a7757c518"
Parent: "161f0b91-74e6-4f6b-a0aa-e37b17ea29a4"
Template: "161f0b91-74e6-4f6b-a0aa-e37b17ea29a4"
Path: /sitecore/templates/Project/Sugcon/Homepage/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{3164213A-4E9D-4C68-B7BF-6B224E23445C}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{2A629F93-718A-4DBA-9155-393C870457F9}">
        <r
          id="{C9593FF9-14AC-4C8E-B217-D85C05ADEAD7}"
          ph="header"
          uid="{D842E8EB-450E-4348-A54A-E60CF16E9E52}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{3EF8E34A-B17B-4512-B395-953C511698AE}"
              p:before="*"
              s:ds="{CD0DE92E-4D6A-4681-B30B-3D0259EF0233}"
              s:id="{A4F28B31-5D18-4158-92AB-F4D2ECA6D2BE}"
              s:par=""
              s:ph="header"
              s:ccb="Clear on publish" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200513T045748Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1da5fd82-50e9-4fac-bdd8-c72e2fcc770c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220303T125646Z
